server:
  # 项目端口号
  port: 6070

spring:
  datasource:
    # MySQL 连接配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.24.147.229:3306/tree?serverTimezone=GMT%2B8
    username: root
    password: 123456
  data:
    # MongoDB 连接配置
    mongodb:
      host: 175.24.147.229
      port: 27018
      database: tree
      username: tree
      password: devtree
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


secure:
  ignored:
    urls:
      - /
      - /swagger-ui/
      - /*.html
      - /favicon.ico
      - /**/*.html
      - /**/*.css
      - /**/*.js
      - /swagger-resources/**
      - /v2/api-docs/**